---
prometheus_version: "3.13.3"

prometheus_user: prometheus
prometheus_group: prometheus

prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_bin_dir: /usr/local/bin

prometheus_archive: "prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_archive }}"

